version: '3.8'

services:
  db:
    image: postgres
    restart: no
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: ${PRIVATE_DB_PASSWORD} # Change this to something more secure in production (duh :-))
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: no
    environment:
      PGADMIN_DEFAULT_EMAIL: alex@alexswensen.io
      PGADMIN_DEFAULT_PASSWORD: ${PRIVATE_DB_PASSWORD} # Change this to something more secure in production (duh :-))
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
